# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 20, 461, 421))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.Aries = QtWidgets.QPushButton(self.groupBox)
        self.Aries.setEnabled(True)
        self.Aries.setGeometry(QtCore.QRect(210, 40, 121, 121))
        self.Aries.setAcceptDrops(False)
        self.Aries.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Aries.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Aries.setIcon(icon)
        self.Aries.setIconSize(QtCore.QSize(128, 128))
        self.Aries.setAutoExclusive(False)
        self.Aries.setFlat(False)
        self.Aries.setObjectName("Aries")
        self.Taurus = QtWidgets.QPushButton(self.groupBox)
        self.Taurus.setGeometry(QtCore.QRect(0, 50, 75, 23))
        self.Taurus.setObjectName("Taurus")
        self.Gemini = QtWidgets.QPushButton(self.groupBox)
        self.Gemini.setGeometry(QtCore.QRect(0, 80, 75, 23))
        self.Gemini.setObjectName("Gemini")
        self.Cancer = QtWidgets.QPushButton(self.groupBox)
        self.Cancer.setGeometry(QtCore.QRect(0, 110, 75, 23))
        self.Cancer.setObjectName("Cancer")
        self.Leo = QtWidgets.QPushButton(self.groupBox)
        self.Leo.setGeometry(QtCore.QRect(0, 140, 75, 23))
        self.Leo.setObjectName("Leo")
        self.Virgo = QtWidgets.QPushButton(self.groupBox)
        self.Virgo.setGeometry(QtCore.QRect(0, 170, 75, 23))
        self.Virgo.setObjectName("Virgo")
        self.Libra = QtWidgets.QPushButton(self.groupBox)
        self.Libra.setGeometry(QtCore.QRect(0, 200, 75, 23))
        self.Libra.setObjectName("Libra")
        self.Scorpio = QtWidgets.QPushButton(self.groupBox)
        self.Scorpio.setGeometry(QtCore.QRect(0, 230, 75, 23))
        self.Scorpio.setObjectName("Scorpio")
        self.Sagittarius = QtWidgets.QPushButton(self.groupBox)
        self.Sagittarius.setGeometry(QtCore.QRect(0, 270, 75, 23))
        self.Sagittarius.setObjectName("Sagittarius")
        self.Capricorn = QtWidgets.QPushButton(self.groupBox)
        self.Capricorn.setGeometry(QtCore.QRect(0, 310, 75, 23))
        self.Capricorn.setObjectName("Capricorn")
        self.Aquarius = QtWidgets.QPushButton(self.groupBox)
        self.Aquarius.setGeometry(QtCore.QRect(0, 350, 75, 23))
        self.Aquarius.setObjectName("Aquarius")
        self.Pisces = QtWidgets.QPushButton(self.groupBox)
        self.Pisces.setGeometry(QtCore.QRect(0, 390, 75, 23))
        self.Pisces.setObjectName("Pisces")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Taurus.setText(_translate("MainWindow", "Телец"))
        self.Gemini.setText(_translate("MainWindow", "Близнецы"))
        self.Cancer.setText(_translate("MainWindow", "Рак"))
        self.Leo.setText(_translate("MainWindow", "Лев"))
        self.Virgo.setText(_translate("MainWindow", "Дева"))
        self.Libra.setText(_translate("MainWindow", "Весы"))
        self.Scorpio.setText(_translate("MainWindow", "Скорпион"))
        self.Sagittarius.setText(_translate("MainWindow", "Стрелец"))
        self.Capricorn.setText(_translate("MainWindow", "Козерог"))
        self.Aquarius.setText(_translate("MainWindow", "Водолей"))
        self.Pisces.setText(_translate("MainWindow", "Рыбы"))
