# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Zodiac(logo).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Aries = QtWidgets.QPushButton(self.centralwidget)
        self.Aries.setEnabled(True)
        self.Aries.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.Aries.setAcceptDrops(False)
        self.Aries.setIconSize(QtCore.QSize(128, 128))
        self.Aries.setAutoExclusive(False)
        self.Aries.setFlat(False)
        self.Aries.setObjectName("Aries")
        self.Taurus = QtWidgets.QPushButton(self.centralwidget)
        self.Taurus.setGeometry(QtCore.QRect(100, 10, 75, 23))
        self.Taurus.setIconSize(QtCore.QSize(128, 128))
        self.Taurus.setObjectName("Taurus")
        self.Gemini = QtWidgets.QPushButton(self.centralwidget)
        self.Gemini.setGeometry(QtCore.QRect(190, 10, 75, 23))
        self.Gemini.setObjectName("Gemini")
        self.Cancer = QtWidgets.QPushButton(self.centralwidget)
        self.Cancer.setGeometry(QtCore.QRect(280, 10, 75, 23))
        self.Cancer.setObjectName("Cancer")
        self.Lion = QtWidgets.QPushButton(self.centralwidget)
        self.Lion.setGeometry(QtCore.QRect(370, 10, 75, 23))
        self.Lion.setObjectName("Lion")
        self.Virgo = QtWidgets.QPushButton(self.centralwidget)
        self.Virgo.setGeometry(QtCore.QRect(460, 10, 75, 23))
        self.Virgo.setObjectName("Virgo")
        self.Libra = QtWidgets.QPushButton(self.centralwidget)
        self.Libra.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.Libra.setObjectName("Libra")
        self.Scorpio = QtWidgets.QPushButton(self.centralwidget)
        self.Scorpio.setGeometry(QtCore.QRect(100, 50, 75, 23))
        self.Scorpio.setObjectName("Scorpio")
        self.Sagittarius = QtWidgets.QPushButton(self.centralwidget)
        self.Sagittarius.setGeometry(QtCore.QRect(190, 50, 75, 23))
        self.Sagittarius.setObjectName("Sagittarius")
        self.Capricorn = QtWidgets.QPushButton(self.centralwidget)
        self.Capricorn.setGeometry(QtCore.QRect(280, 50, 75, 23))
        self.Capricorn.setObjectName("Capricorn")
        self.Aquarius = QtWidgets.QPushButton(self.centralwidget)
        self.Aquarius.setGeometry(QtCore.QRect(370, 50, 75, 23))
        self.Aquarius.setObjectName("Aquarius")
        self.Pisces = QtWidgets.QPushButton(self.centralwidget)
        self.Pisces.setGeometry(QtCore.QRect(460, 50, 75, 23))
        self.Pisces.setObjectName("Pisces")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 100, 81, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(110, 130, 391, 181))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Zodiac"))
        self.Aries.setText(_translate("MainWindow", "Овен"))
        self.Taurus.setText(_translate("MainWindow", "Телец"))
        self.Gemini.setText(_translate("MainWindow", "Близнецы"))
        self.Cancer.setText(_translate("MainWindow", "Рак"))
        self.Lion.setText(_translate("MainWindow", "Лев"))
        self.Virgo.setText(_translate("MainWindow", "Дева"))
        self.Libra.setText(_translate("MainWindow", "Весы"))
        self.Scorpio.setText(_translate("MainWindow", "Скорпион"))
        self.Sagittarius.setText(_translate("MainWindow", "Стрелец"))
        self.Capricorn.setText(_translate("MainWindow", "Козерог"))
        self.Aquarius.setText(_translate("MainWindow", "Водолей"))
        self.Pisces.setText(_translate("MainWindow", "Рыбы"))
        self.comboBox.setCurrentText(_translate("MainWindow", "На сегодня"))
        self.comboBox.setItemText(0, _translate("MainWindow", "На вчера"))
        self.comboBox.setItemText(1, _translate("MainWindow", "На сегодня"))
        self.comboBox.setItemText(2, _translate("MainWindow", "На завтра"))
        self.comboBox.setItemText(3, _translate("MainWindow", "На неделю"))
        self.comboBox.setItemText(4, _translate("MainWindow", "На месяц"))
        self.comboBox.setItemText(5, _translate("MainWindow", "На год"))

        self.Aries.clicked.connect(lambda: self.printer(self.Aries))
        self.Taurus.clicked.connect(lambda: self.printer(self.Taurus))
        self.Gemini.clicked.connect(lambda: self.printer(self.Gemini))
        self.Cancer.clicked.connect(lambda: self.printer(self.Cancer))
        self.Lion.clicked.connect(lambda: self.printer(self.Lion))
        self.Virgo.clicked.connect(lambda: self.printer(self.Virgo))
        self.Libra.clicked.connect(lambda: self.printer(self.Libra))
        self.Scorpio.clicked.connect(lambda: self.printer(self.Scorpio))
        self.Sagittarius.clicked.connect(lambda: self.printer(self.Sagittarius))
        self.Capricorn.clicked.connect(lambda: self.printer(self.Capricorn))
        self.Aquarius.clicked.connect(lambda: self.printer(self.Aquarius))
        self.Pisces.clicked.connect(lambda: self.printer(self.Pisces))

    def printer(self, btn):
        self.textBrowser.clear()
        self.btn = btn
        name = self.btn.objectName().lower()
        timesForHoro = {'На вчера': 'yesterday', 'На сегодня': 'today', 'На завтра': 'tomorrow', 'На неделю': 'week',
                     'На месяц': 'month', 'На год': 'year'}
        interval = timesForHoro[self.comboBox.currentText()]
        horo = Parser(name, interval)
        horo.parsing()
        horo.print_horo()
        self.textBrowser.append(horo.print_horo())

if __name__ == "__main__":
    import sys
    from parser import Parser

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
